# This file has been generated by node2nix 1.11.1. Do not edit!
{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [],
}: let
  sources = {
    "@braintree/sanitize-url-6.0.2" = {
      name = "_at_braintree_slash_sanitize-url";
      packageName = "@braintree/sanitize-url";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@braintree/sanitize-url/-/sanitize-url-6.0.2.tgz";
        sha512 = "Tbsj02wXCbqGmzdnXNk0SOF19ChhRU70BsroIi4Pm6Ehp56in6vch94mfbdQ17DozxkL3BAVjbZ4Qc1a0HFRAg==";
      };
    };
    "@types/debug-4.1.8" = {
      name = "_at_types_slash_debug";
      packageName = "@types/debug";
      version = "4.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/debug/-/debug-4.1.8.tgz";
        sha512 = "/vPO1EPOs306Cvhwv7KfVfYvOJqA/S/AXjaHQiJboCZzcNDb+TIJFN9/2C9DZ//ijSKWioNyUxD792QmDJ+HKQ==";
      };
    };
    "@types/mdast-3.0.11" = {
      name = "_at_types_slash_mdast";
      packageName = "@types/mdast";
      version = "3.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/mdast/-/mdast-3.0.11.tgz";
        sha512 = "Y/uImid8aAwrEA24/1tcRZwpxX3pIFTSilcNDKSPn+Y2iDywSEachzRuvgAYYLR3wpGXAsMbv5lvKLDZLeYPAw==";
      };
    };
    "@types/ms-0.7.31" = {
      name = "_at_types_slash_ms";
      packageName = "@types/ms";
      version = "0.7.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/ms/-/ms-0.7.31.tgz";
        sha512 = "iiUgKzV9AuaEkZqkOLDIvlQiL6ltuZd9tGcW3gwpnX8JbuiuhFlEGmmFXEXkN50Cvq7Os88IY2v0dkDqXYWVgA==";
      };
    };
    "@types/unist-2.0.6" = {
      name = "_at_types_slash_unist";
      packageName = "@types/unist";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/unist/-/unist-2.0.6.tgz";
        sha512 = "PBjIUxZHOuj0R15/xuwJYjFi+KZdNFrehocChv4g5hu6aFroHue8m0lBP0POdK2nKzbw0cgV1mws8+V/JAcEkQ==";
      };
    };
    "agent-base-4.3.0" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-4.3.0.tgz";
        sha512 = "salcGninV0nPrwpGNn4VTXBb1SOuXQBiqbrNXoeizJsHrsL6ERFM2Ne3JUSBWRE6aeNJI2ROP/WEEIDUiDe3cg==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "async-limiter-1.0.1" = {
      name = "async-limiter";
      packageName = "async-limiter";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-limiter/-/async-limiter-1.0.1.tgz";
        sha512 = "csOlWGAcRFJaI6m+F2WKdnMKr4HhdhFVBk0H/QbJFMCr+uO2kwohwXQPxw/9OCxp05r5ghVBFSyioixx3gfkNQ==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "buffer-crc32-0.2.13" = {
      name = "buffer-crc32";
      packageName = "buffer-crc32";
      version = "0.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.13.tgz";
        sha512 = "VO9Ht/+p3SN7SKWqcrgEzjGbRSJYTx+Q1pTQC0wrWqHx0vpJraQ6GtHx8tvcg1rlK1byhU5gccxgOgj7B0TDkQ==";
      };
    };
    "buffer-from-1.1.2" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.2.tgz";
        sha512 = "E+XQCRwSbaaiChtv6k6Dwgc+bx+Bs6vuKJHHl5kox/BaKbhiXzqQOwK4cO22yElGp2OCmjwVhT3HmxgyPGnJfQ==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "character-entities-2.0.2" = {
      name = "character-entities";
      packageName = "character-entities";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-entities/-/character-entities-2.0.2.tgz";
        sha512 = "shx7oQ0Awen/BRIdkjkvz54PnEEI/EjwXDSIZp86/KKdbafHh1Df/RYGBhn4hbe2+uKC9FnT5UCEdyPz3ai9hQ==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha512 = "72fSenhMw2HZMTVHeCA9KCmpEIbzWiQsjN+BHcBbS9vr1mtt+vJjPdksIBNUmKAW8TFUDPJK5SUU3QhE9NEXDw==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "commander-7.2.0" = {
      name = "commander";
      packageName = "commander";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-7.2.0.tgz";
        sha512 = "QrWXB+ZQSVPmIWIhtEO9H+gwHaMGYiF5ChvoJ+K9ZGHG/sVsa6yiesAD1GC/x46sET00Xlwo1u49RVVVzvcSkw==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "concat-stream-1.6.2" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.2.tgz";
        sha512 = "27HBghJxjiZtIk3Ycvn/4kbJk/1uZuJFfuPEns6LaEvpvG1f0hTea8lilrouyo9mVc2GWdcEZ8OLoGmSADlrCw==";
      };
    };
    "core-util-is-1.0.3" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.3.tgz";
        sha512 = "ZQBvi1DcpJ4GDqanjucZ2Hj3wEO5pZDS89BWbkcrvdxksJorwUDDZamX9ldFkp9aw2lmBDLgkObEA4DWNJ9FYQ==";
      };
    };
    "core_d-5.0.1" = {
      name = "core_d";
      packageName = "core_d";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/core_d/-/core_d-5.0.1.tgz";
        sha512 = "37lZyhJY1hzgFbfU4LzY4zL09QPwPfV2W/3YBOtN7mkdvVaeP1OVnDZI6zxggtlPwG/BuE5wIr0xptlVJk5EPA==";
      };
    };
    "cose-base-1.0.3" = {
      name = "cose-base";
      packageName = "cose-base";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cose-base/-/cose-base-1.0.3.tgz";
        sha512 = "s9whTXInMSgAp/NVXVNuVxVKzGH2qck3aQlVHxDCdAEPgtMKwc4Wq6/QKhgdEdgbLSi9rBTAcPoRa6JpiG4ksg==";
      };
    };
    "cose-base-2.2.0" = {
      name = "cose-base";
      packageName = "cose-base";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cose-base/-/cose-base-2.2.0.tgz";
        sha512 = "AzlgcsCbUMymkADOJtQm3wO9S3ltPfYOFD5033keQn9NJzIbtnZj+UdBJe7DYml/8TdbtHJW3j58SOnKhWY/5g==";
      };
    };
    "cytoscape-3.25.0" = {
      name = "cytoscape";
      packageName = "cytoscape";
      version = "3.25.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cytoscape/-/cytoscape-3.25.0.tgz";
        sha512 = "7MW3Iz57mCUo6JQCho6CmPBCbTlJr7LzyEtIkutG255HLVd4XuBg2I9BkTZLI/e4HoaOB/BiAzXuQybQ95+r9Q==";
      };
    };
    "cytoscape-cose-bilkent-4.1.0" = {
      name = "cytoscape-cose-bilkent";
      packageName = "cytoscape-cose-bilkent";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cytoscape-cose-bilkent/-/cytoscape-cose-bilkent-4.1.0.tgz";
        sha512 = "wgQlVIUJF13Quxiv5e1gstZ08rnZj2XaLHGoFMYXz7SkNfCDOOteKBE6SYRfA9WxxI/iBc3ajfDoc6hb/MRAHQ==";
      };
    };
    "cytoscape-fcose-2.2.0" = {
      name = "cytoscape-fcose";
      packageName = "cytoscape-fcose";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cytoscape-fcose/-/cytoscape-fcose-2.2.0.tgz";
        sha512 = "ki1/VuRIHFCzxWNrsshHYPs6L7TvLu3DL+TyIGEsRcvVERmxokbf5Gdk7mFxZnTdiGtnA4cfSmjZJMviqSuZrQ==";
      };
    };
    "d3-7.8.5" = {
      name = "d3";
      packageName = "d3";
      version = "7.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3/-/d3-7.8.5.tgz";
        sha512 = "JgoahDG51ncUfJu6wX/1vWQEqOflgXyl4MaHqlcSruTez7yhaRKR9i8VjjcQGeS2en/jnFivXuaIMnseMMt0XA==";
      };
    };
    "d3-array-3.2.4" = {
      name = "d3-array";
      packageName = "d3-array";
      version = "3.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-array/-/d3-array-3.2.4.tgz";
        sha512 = "tdQAmyA18i4J7wprpYq8ClcxZy3SC31QMeByyCFyRt7BVHdREQZ5lpzoe5mFEYZUWe+oq8HBvk9JjpibyEV4Jg==";
      };
    };
    "d3-axis-3.0.0" = {
      name = "d3-axis";
      packageName = "d3-axis";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-axis/-/d3-axis-3.0.0.tgz";
        sha512 = "IH5tgjV4jE/GhHkRV0HiVYPDtvfjHQlQfJHs0usq7M30XcSBvOotpmH1IgkcXsO/5gEQZD43B//fc7SRT5S+xw==";
      };
    };
    "d3-brush-3.0.0" = {
      name = "d3-brush";
      packageName = "d3-brush";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-brush/-/d3-brush-3.0.0.tgz";
        sha512 = "ALnjWlVYkXsVIGlOsuWH1+3udkYFI48Ljihfnh8FZPF2QS9o+PzGLBslO0PjzVoHLZ2KCVgAM8NVkXPJB2aNnQ==";
      };
    };
    "d3-chord-3.0.1" = {
      name = "d3-chord";
      packageName = "d3-chord";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-chord/-/d3-chord-3.0.1.tgz";
        sha512 = "VE5S6TNa+j8msksl7HwjxMHDM2yNK3XCkusIlpX5kwauBfXuyLAtNg9jCp/iHH61tgI4sb6R/EIMWCqEIdjT/g==";
      };
    };
    "d3-color-3.1.0" = {
      name = "d3-color";
      packageName = "d3-color";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-color/-/d3-color-3.1.0.tgz";
        sha512 = "zg/chbXyeBtMQ1LbD/WSoW2DpC3I0mpmPdW+ynRTj/x2DAWYrIY7qeZIHidozwV24m4iavr15lNwIwLxRmOxhA==";
      };
    };
    "d3-contour-4.0.2" = {
      name = "d3-contour";
      packageName = "d3-contour";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-contour/-/d3-contour-4.0.2.tgz";
        sha512 = "4EzFTRIikzs47RGmdxbeUvLWtGedDUNkTcmzoeyg4sP/dvCexO47AaQL7VKy/gul85TOxw+IBgA8US2xwbToNA==";
      };
    };
    "d3-delaunay-6.0.4" = {
      name = "d3-delaunay";
      packageName = "d3-delaunay";
      version = "6.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-delaunay/-/d3-delaunay-6.0.4.tgz";
        sha512 = "mdjtIZ1XLAM8bm/hx3WwjfHt6Sggek7qH043O8KEjDXN40xi3vx/6pYSVTwLjEgiXQTbvaouWKynLBiUZ6SK6A==";
      };
    };
    "d3-dispatch-3.0.1" = {
      name = "d3-dispatch";
      packageName = "d3-dispatch";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-dispatch/-/d3-dispatch-3.0.1.tgz";
        sha512 = "rzUyPU/S7rwUflMyLc1ETDeBj0NRuHKKAcvukozwhshr6g6c5d8zh4c2gQjY2bZ0dXeGLWc1PF174P2tVvKhfg==";
      };
    };
    "d3-drag-3.0.0" = {
      name = "d3-drag";
      packageName = "d3-drag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-drag/-/d3-drag-3.0.0.tgz";
        sha512 = "pWbUJLdETVA8lQNJecMxoXfH6x+mO2UQo8rSmZ+QqxcbyA3hfeprFgIT//HW2nlHChWeIIMwS2Fq+gEARkhTkg==";
      };
    };
    "d3-dsv-3.0.1" = {
      name = "d3-dsv";
      packageName = "d3-dsv";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-dsv/-/d3-dsv-3.0.1.tgz";
        sha512 = "UG6OvdI5afDIFP9w4G0mNq50dSOsXHJaRE8arAS5o9ApWnIElp8GZw1Dun8vP8OyHOZ/QJUKUJwxiiCCnUwm+Q==";
      };
    };
    "d3-ease-3.0.1" = {
      name = "d3-ease";
      packageName = "d3-ease";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-ease/-/d3-ease-3.0.1.tgz";
        sha512 = "wR/XK3D3XcLIZwpbvQwQ5fK+8Ykds1ip7A2Txe0yxncXSdq1L9skcG7blcedkOX+ZcgxGAmLX1FrRGbADwzi0w==";
      };
    };
    "d3-fetch-3.0.1" = {
      name = "d3-fetch";
      packageName = "d3-fetch";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-fetch/-/d3-fetch-3.0.1.tgz";
        sha512 = "kpkQIM20n3oLVBKGg6oHrUchHM3xODkTzjMoj7aWQFq5QEM+R6E4WkzT5+tojDY7yjez8KgCBRoj4aEr99Fdqw==";
      };
    };
    "d3-force-3.0.0" = {
      name = "d3-force";
      packageName = "d3-force";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-force/-/d3-force-3.0.0.tgz";
        sha512 = "zxV/SsA+U4yte8051P4ECydjD/S+qeYtnaIyAs9tgHCqfguma/aAQDjo85A9Z6EKhBirHRJHXIgJUlffT4wdLg==";
      };
    };
    "d3-format-3.1.0" = {
      name = "d3-format";
      packageName = "d3-format";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-format/-/d3-format-3.1.0.tgz";
        sha512 = "YyUI6AEuY/Wpt8KWLgZHsIU86atmikuoOmCfommt0LYHiQSPjvX2AcFc38PX0CBpr2RCyZhjex+NS/LPOv6YqA==";
      };
    };
    "d3-geo-3.1.0" = {
      name = "d3-geo";
      packageName = "d3-geo";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-geo/-/d3-geo-3.1.0.tgz";
        sha512 = "JEo5HxXDdDYXCaWdwLRt79y7giK8SbhZJbFWXqbRTolCHFI5jRqteLzCsq51NKbUoX0PjBVSohxrx+NoOUujYA==";
      };
    };
    "d3-hierarchy-3.1.2" = {
      name = "d3-hierarchy";
      packageName = "d3-hierarchy";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-hierarchy/-/d3-hierarchy-3.1.2.tgz";
        sha512 = "FX/9frcub54beBdugHjDCdikxThEqjnR93Qt7PvQTOHxyiNCAlvMrHhclk3cD5VeAaq9fxmfRp+CnWw9rEMBuA==";
      };
    };
    "d3-interpolate-3.0.1" = {
      name = "d3-interpolate";
      packageName = "d3-interpolate";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-interpolate/-/d3-interpolate-3.0.1.tgz";
        sha512 = "3bYs1rOD33uo8aqJfKP3JWPAibgw8Zm2+L9vBKEHJ2Rg+viTR7o5Mmv5mZcieN+FRYaAOWX5SJATX6k1PWz72g==";
      };
    };
    "d3-path-3.1.0" = {
      name = "d3-path";
      packageName = "d3-path";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-path/-/d3-path-3.1.0.tgz";
        sha512 = "p3KP5HCf/bvjBSSKuXid6Zqijx7wIfNW+J/maPs+iwR35at5JCbLUT0LzF1cnjbCHWhqzQTIN2Jpe8pRebIEFQ==";
      };
    };
    "d3-polygon-3.0.1" = {
      name = "d3-polygon";
      packageName = "d3-polygon";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-polygon/-/d3-polygon-3.0.1.tgz";
        sha512 = "3vbA7vXYwfe1SYhED++fPUQlWSYTTGmFmQiany/gdbiWgU/iEyQzyymwL9SkJjFFuCS4902BSzewVGsHHmHtXg==";
      };
    };
    "d3-quadtree-3.0.1" = {
      name = "d3-quadtree";
      packageName = "d3-quadtree";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-quadtree/-/d3-quadtree-3.0.1.tgz";
        sha512 = "04xDrxQTDTCFwP5H6hRhsRcb9xxv2RzkcsygFzmkSIOJy3PeRJP7sNk3VRIbKXcog561P9oU0/rVH6vDROAgUw==";
      };
    };
    "d3-random-3.0.1" = {
      name = "d3-random";
      packageName = "d3-random";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-random/-/d3-random-3.0.1.tgz";
        sha512 = "FXMe9GfxTxqd5D6jFsQ+DJ8BJS4E/fT5mqqdjovykEB2oFbTMDVdg1MGFxfQW+FBOGoB++k8swBrgwSHT1cUXQ==";
      };
    };
    "d3-scale-4.0.2" = {
      name = "d3-scale";
      packageName = "d3-scale";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-scale/-/d3-scale-4.0.2.tgz";
        sha512 = "GZW464g1SH7ag3Y7hXjf8RoUuAFIqklOAq3MRl4OaWabTFJY9PN/E1YklhXLh+OQ3fM9yS2nOkCoS+WLZ6kvxQ==";
      };
    };
    "d3-scale-chromatic-3.0.0" = {
      name = "d3-scale-chromatic";
      packageName = "d3-scale-chromatic";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-scale-chromatic/-/d3-scale-chromatic-3.0.0.tgz";
        sha512 = "Lx9thtxAKrO2Pq6OO2Ua474opeziKr279P/TKZsMAhYyNDD3EnCffdbgeSYN5O7m2ByQsxtuP2CSDczNUIZ22g==";
      };
    };
    "d3-selection-3.0.0" = {
      name = "d3-selection";
      packageName = "d3-selection";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-selection/-/d3-selection-3.0.0.tgz";
        sha512 = "fmTRWbNMmsmWq6xJV8D19U/gw/bwrHfNXxrIN+HfZgnzqTHp9jOmKMhsTUjXOJnZOdZY9Q28y4yebKzqDKlxlQ==";
      };
    };
    "d3-shape-3.2.0" = {
      name = "d3-shape";
      packageName = "d3-shape";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-shape/-/d3-shape-3.2.0.tgz";
        sha512 = "SaLBuwGm3MOViRq2ABk3eLoxwZELpH6zhl3FbAoJ7Vm1gofKx6El1Ib5z23NUEhF9AsGl7y+dzLe5Cw2AArGTA==";
      };
    };
    "d3-time-3.1.0" = {
      name = "d3-time";
      packageName = "d3-time";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-time/-/d3-time-3.1.0.tgz";
        sha512 = "VqKjzBLejbSMT4IgbmVgDjpkYrNWUYJnbCGo874u7MMKIWsILRX+OpX/gTk8MqjpT1A/c6HY2dCA77ZN0lkQ2Q==";
      };
    };
    "d3-time-format-4.1.0" = {
      name = "d3-time-format";
      packageName = "d3-time-format";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-time-format/-/d3-time-format-4.1.0.tgz";
        sha512 = "dJxPBlzC7NugB2PDLwo9Q8JiTR3M3e4/XANkreKSUxF8vvXKqm1Yfq4Q5dl8budlunRVlUUaDUgFt7eA8D6NLg==";
      };
    };
    "d3-timer-3.0.1" = {
      name = "d3-timer";
      packageName = "d3-timer";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-timer/-/d3-timer-3.0.1.tgz";
        sha512 = "ndfJ/JxxMd3nw31uyKoY2naivF+r29V+Lc0svZxe1JvvIRmi8hUsrMvdOwgS1o6uBHmiz91geQ0ylPP0aj1VUA==";
      };
    };
    "d3-transition-3.0.1" = {
      name = "d3-transition";
      packageName = "d3-transition";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-transition/-/d3-transition-3.0.1.tgz";
        sha512 = "ApKvfjsSR6tg06xrL434C0WydLr7JewBB3V+/39RMHsaXTOG0zmt/OAXeng5M5LBm0ojmxJrpomQVZ1aPvBL4w==";
      };
    };
    "d3-zoom-3.0.0" = {
      name = "d3-zoom";
      packageName = "d3-zoom";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-zoom/-/d3-zoom-3.0.0.tgz";
        sha512 = "b8AmV3kfQaqWAuacbPuNbL6vahnOJflOhexLzMMNLga62+/nh0JzvJ0aO/5a5MVgUFGS7Hu1P9P03o3fJkDCyw==";
      };
    };
    "dagre-d3-es-7.0.10" = {
      name = "dagre-d3-es";
      packageName = "dagre-d3-es";
      version = "7.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/dagre-d3-es/-/dagre-d3-es-7.0.10.tgz";
        sha512 = "qTCQmEhcynucuaZgY5/+ti3X/rnszKZhEQH/ZdWdtP1tA/y3VoHJzcVrO9pjjJCNpigfscAtoUB5ONcd2wNn0A==";
      };
    };
    "dayjs-1.11.8" = {
      name = "dayjs";
      packageName = "dayjs";
      version = "1.11.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/dayjs/-/dayjs-1.11.8.tgz";
        sha512 = "LcgxzFoWMEPO7ggRv1Y2N31hUf2R0Vj7fuy/m+Bg1K8rr+KAs1AEy4y9jd5DXe8pbHgX+srkHNS7TH6Q6ZhYeQ==";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "debug-3.2.7" = {
      name = "debug";
      packageName = "debug";
      version = "3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.2.7.tgz";
        sha512 = "CFjzYYAi4ThfiQvizrFQevTTXHtnCqWfe7x1AhgEscTz6ZbLbfoLRLPugTQyBth6f8ZERVUSyWHFD/7Wu4t1XQ==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "decode-named-character-reference-1.0.2" = {
      name = "decode-named-character-reference";
      packageName = "decode-named-character-reference";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-named-character-reference/-/decode-named-character-reference-1.0.2.tgz";
        sha512 = "O8x12RzrUF8xyVcY0KJowWsmaJxQbmy0/EtnNtHRpsOcT7dFk5W598coHqBVpmWo1oQQfsCqfCmkZN5DJrZVdg==";
      };
    };
    "delaunator-5.0.0" = {
      name = "delaunator";
      packageName = "delaunator";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delaunator/-/delaunator-5.0.0.tgz";
        sha512 = "AyLvtyJdbv/U1GkiS6gUUzclRoAY4Gs75qkMygJJhU75LW4DNuSF2RMzpxs9jw9Oz1BobHjTdkG3zdP55VxAqw==";
      };
    };
    "dequal-2.0.3" = {
      name = "dequal";
      packageName = "dequal";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dequal/-/dequal-2.0.3.tgz";
        sha512 = "0je+qPKHEMohvfRTCEo3CrPG6cAzAYgmzKyxRiYSSDkS6eGJdyVJm7WaYA5ECaAD9wLB2T4EEeymA5aFVcYXCA==";
      };
    };
    "diff-5.1.0" = {
      name = "diff";
      packageName = "diff";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/diff/-/diff-5.1.0.tgz";
        sha512 = "D+mk+qE8VC/PAUrlAU34N+VfXev0ghe5ywmpqrawphmVZc1bEfn56uo9qpyGp1p4xpzOHkSW4ztBd6L7Xx4ACw==";
      };
    };
    "dompurify-3.0.3" = {
      name = "dompurify";
      packageName = "dompurify";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dompurify/-/dompurify-3.0.3.tgz";
        sha512 = "axQ9zieHLnAnHh0sfAamKYiqXMJAVwu+LM/alQ7WDagoWessyWvMSFyW65CqF3owufNu8HBcE4cM2Vflu7YWcQ==";
      };
    };
    "elkjs-0.8.2" = {
      name = "elkjs";
      packageName = "elkjs";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/elkjs/-/elkjs-0.8.2.tgz";
        sha512 = "L6uRgvZTH+4OF5NE/MBbzQx/WYpru1xCBE9respNj6qznEewGUIfhzmm7horWWxbNO2M0WckQypGctR8lH79xQ==";
      };
    };
    "es6-promise-4.2.8" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "4.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-4.2.8.tgz";
        sha512 = "HJDGx5daxeIvxdBxvG2cb9g4tEvwIk3i8+nhX0yGrYmZUzbkdg8QbDevheDB8gd0//uPj4c1EQua8Q+MViT0/w==";
      };
    };
    "es6-promisify-5.0.0" = {
      name = "es6-promisify";
      packageName = "es6-promisify";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promisify/-/es6-promisify-5.0.0.tgz";
        sha512 = "C+d6UdsYDk0lMebHNR4S2NybQMMngAOnOwYBQjTOiv0MkoJMP0Myw2mgpDLBcpfCmRLxyFqYhS/CfOENq4SJhQ==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha512 = "vbRorB5FUQWvla16U8R/qgaFIya2qGzwDrNmCZuYKrbdSUMG6I1ZCGQRefkRVhuOkIGVne7BQ35DSfo1qvJqFg==";
      };
    };
    "extract-zip-1.7.0" = {
      name = "extract-zip";
      packageName = "extract-zip";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extract-zip/-/extract-zip-1.7.0.tgz";
        sha512 = "xoh5G1W/PB0/27lXgMQyIhP5DSY/LhoCsOyZgb+6iMmRtCwVBo55uKaMoEYrDCKQhWvqEip5ZPKAc6eFNyf/MA==";
      };
    };
    "fd-slicer-1.1.0" = {
      name = "fd-slicer";
      packageName = "fd-slicer";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fd-slicer/-/fd-slicer-1.1.0.tgz";
        sha512 = "cE1qsB/VwyQozZ+q1dGxR8LBYNZeofhEdUNGSMbQD3Gw2lAzX9Zb3uIU6Ebc/Fmyjo9AWWfnn0AUCHqtevs/8g==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha512 = "OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==";
      };
    };
    "glob-7.2.3" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.3.tgz";
        sha512 = "nFR0zLpU2YCaRxwoCJvL6UvCH2JFyFVIvwTLsIf21AuHlMskA1hhTdk+LlYJtOlYt9v6dvszD2BGRqBL+iQK9Q==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha512 = "sKJf1+ceQBr4SMkvQnBDNDtf4TXpVhVGateu0t918bl30FnbE2m4vNLX+VWe/dpjlb+HugGYzW7uQXH98HPEYw==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "heap-0.2.7" = {
      name = "heap";
      packageName = "heap";
      version = "0.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/heap/-/heap-0.2.7.tgz";
        sha512 = "2bsegYkkHO+h/9MGbn6KWcE45cHZgPANo5LXF7EvWdT0yT2EguSVO1nDgU5c8+ZOPwp2vMNa7YFsJhVcDR9Sdg==";
      };
    };
    "https-proxy-agent-2.2.4" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-2.2.4.tgz";
        sha512 = "OmvfoQ53WLjtA9HeYP9RNrWMJzzAz1JGaSFr1nijg0PVR1JaD/xbJq1mdEIIlxGpXp9eSe/O2LgU9DJmTPd0Eg==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha512 = "k92I/b08q4wvFscXCLvqfsHCrjrF7yiXsQuIVvVE7N82W3+aqpzuUdBbfhWcy/FZR3/4IgflMgKLOsvPDrGCJA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "internmap-2.0.3" = {
      name = "internmap";
      packageName = "internmap";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/internmap/-/internmap-2.0.3.tgz";
        sha512 = "5Hh7Y1wQbvY5ooGgPbDaL5iYLAPzMTUrjMulskHLH6wnv/A+1q5rgEaiuqEjB+oxGXIVZs1FF+R/KPN3ZSQYYg==";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha512 = "VLghIWNM6ELQzo7zwmcg0NmTVyWKYjvIeM83yjp0wRDTmUnrM678fQbcKBo6n2CJEF0szoG//ytg+TKla89ALQ==";
      };
    };
    "khroma-2.0.0" = {
      name = "khroma";
      packageName = "khroma";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/khroma/-/khroma-2.0.0.tgz";
        sha512 = "2J8rDNlQWbtiNYThZRvmMv5yt44ZakX+Tz5ZIp/mN1pt4snn+m030Va5Z4v8xA0cQFDXBwO/8i42xL4QPsVk3g==";
      };
    };
    "kleur-4.1.5" = {
      name = "kleur";
      packageName = "kleur";
      version = "4.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/kleur/-/kleur-4.1.5.tgz";
        sha512 = "o+NO+8WrRiQEE4/7nwRJhN1HWpVmJm511pBHUxPLtp0BUISzlBplORYSmTclCnJvQq2tKu/sgl3xVpkc7ZWuQQ==";
      };
    };
    "layout-base-1.0.2" = {
      name = "layout-base";
      packageName = "layout-base";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/layout-base/-/layout-base-1.0.2.tgz";
        sha512 = "8h2oVEZNktL4BH2JCOI90iD1yXwL6iNW7KcCKT2QZgQJR2vbqDsldCTPRU9NifTCqHZci57XvQQ15YTu+sTYPg==";
      };
    };
    "layout-base-2.0.1" = {
      name = "layout-base";
      packageName = "layout-base";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/layout-base/-/layout-base-2.0.1.tgz";
        sha512 = "dp3s92+uNI1hWIpPGH3jK2kxE2lMjdXdr+DH8ynZHpd6PUlH6x6cbuXnoMmiNumznqaNO31xu9e79F0uuZ0JFg==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lodash-es-4.17.21" = {
      name = "lodash-es";
      packageName = "lodash-es";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash-es/-/lodash-es-4.17.21.tgz";
        sha512 = "mKnC+QJ9pWVzv+C4/U3rRsHapFfHvQFoFB92e52xeyGMcX6/OlIl78je1u8vePzYZSkkogMPJ2yjxxsb89cxyw==";
      };
    };
    "mdast-util-from-markdown-1.3.1" = {
      name = "mdast-util-from-markdown";
      packageName = "mdast-util-from-markdown";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-from-markdown/-/mdast-util-from-markdown-1.3.1.tgz";
        sha512 = "4xTO/M8c82qBcnQc1tgpNtubGUW/Y1tBQ1B0i5CtSoelOLKFYlElIr3bvgREYYO5iRqbMY1YuqZng0GVOI8Qww==";
      };
    };
    "mdast-util-to-string-3.2.0" = {
      name = "mdast-util-to-string";
      packageName = "mdast-util-to-string";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-to-string/-/mdast-util-to-string-3.2.0.tgz";
        sha512 = "V4Zn/ncyN1QNSqSBxTrMOLpjr+IKdHl2v3KVLoWmDPscP4r9GcCi71gjgvUV1SFSKh92AjAG4peFuBl2/YgCJg==";
      };
    };
    "micromark-3.2.0" = {
      name = "micromark";
      packageName = "micromark";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark/-/micromark-3.2.0.tgz";
        sha512 = "uD66tJj54JLYq0De10AhWycZWGQNUvDI55xPgk2sQM5kn1JYlhbCMTtEeT27+vAhW2FBQxLlOmS3pmA7/2z4aA==";
      };
    };
    "micromark-core-commonmark-1.1.0" = {
      name = "micromark-core-commonmark";
      packageName = "micromark-core-commonmark";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-core-commonmark/-/micromark-core-commonmark-1.1.0.tgz";
        sha512 = "BgHO1aRbolh2hcrzL2d1La37V0Aoz73ymF8rAcKnohLy93titmv62E0gP8Hrx9PKcKrqCZ1BbLGbP3bEhoXYlw==";
      };
    };
    "micromark-factory-destination-1.1.0" = {
      name = "micromark-factory-destination";
      packageName = "micromark-factory-destination";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-destination/-/micromark-factory-destination-1.1.0.tgz";
        sha512 = "XaNDROBgx9SgSChd69pjiGKbV+nfHGDPVYFs5dOoDd7ZnMAE+Cuu91BCpsY8RT2NP9vo/B8pds2VQNCLiu0zhg==";
      };
    };
    "micromark-factory-label-1.1.0" = {
      name = "micromark-factory-label";
      packageName = "micromark-factory-label";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-label/-/micromark-factory-label-1.1.0.tgz";
        sha512 = "OLtyez4vZo/1NjxGhcpDSbHQ+m0IIGnT8BoPamh+7jVlzLJBH98zzuCoUeMxvM6WsNeh8wx8cKvqLiPHEACn0w==";
      };
    };
    "micromark-factory-space-1.1.0" = {
      name = "micromark-factory-space";
      packageName = "micromark-factory-space";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-space/-/micromark-factory-space-1.1.0.tgz";
        sha512 = "cRzEj7c0OL4Mw2v6nwzttyOZe8XY/Z8G0rzmWQZTBi/jjwyw/U4uqKtUORXQrR5bAZZnbTI/feRV/R7hc4jQYQ==";
      };
    };
    "micromark-factory-title-1.1.0" = {
      name = "micromark-factory-title";
      packageName = "micromark-factory-title";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-title/-/micromark-factory-title-1.1.0.tgz";
        sha512 = "J7n9R3vMmgjDOCY8NPw55jiyaQnH5kBdV2/UXCtZIpnHH3P6nHUKaH7XXEYuWwx/xUJcawa8plLBEjMPU24HzQ==";
      };
    };
    "micromark-factory-whitespace-1.1.0" = {
      name = "micromark-factory-whitespace";
      packageName = "micromark-factory-whitespace";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-whitespace/-/micromark-factory-whitespace-1.1.0.tgz";
        sha512 = "v2WlmiymVSp5oMg+1Q0N1Lxmt6pMhIHD457whWM7/GUlEks1hI9xj5w3zbc4uuMKXGisksZk8DzP2UyGbGqNsQ==";
      };
    };
    "micromark-util-character-1.2.0" = {
      name = "micromark-util-character";
      packageName = "micromark-util-character";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-character/-/micromark-util-character-1.2.0.tgz";
        sha512 = "lXraTwcX3yH/vMDaFWCQJP1uIszLVebzUa3ZHdrgxr7KEU/9mL4mVgCpGbyhvNLNlauROiNUq7WN5u7ndbY6xg==";
      };
    };
    "micromark-util-chunked-1.1.0" = {
      name = "micromark-util-chunked";
      packageName = "micromark-util-chunked";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-chunked/-/micromark-util-chunked-1.1.0.tgz";
        sha512 = "Ye01HXpkZPNcV6FiyoW2fGZDUw4Yc7vT0E9Sad83+bEDiCJ1uXu0S3mr8WLpsz3HaG3x2q0HM6CTuPdcZcluFQ==";
      };
    };
    "micromark-util-classify-character-1.1.0" = {
      name = "micromark-util-classify-character";
      packageName = "micromark-util-classify-character";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-classify-character/-/micromark-util-classify-character-1.1.0.tgz";
        sha512 = "SL0wLxtKSnklKSUplok1WQFoGhUdWYKggKUiqhX+Swala+BtptGCu5iPRc+xvzJ4PXE/hwM3FNXsfEVgoZsWbw==";
      };
    };
    "micromark-util-combine-extensions-1.1.0" = {
      name = "micromark-util-combine-extensions";
      packageName = "micromark-util-combine-extensions";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-combine-extensions/-/micromark-util-combine-extensions-1.1.0.tgz";
        sha512 = "Q20sp4mfNf9yEqDL50WwuWZHUrCO4fEyeDCnMGmG5Pr0Cz15Uo7KBs6jq+dq0EgX4DPwwrh9m0X+zPV1ypFvUA==";
      };
    };
    "micromark-util-decode-numeric-character-reference-1.1.0" = {
      name = "micromark-util-decode-numeric-character-reference";
      packageName = "micromark-util-decode-numeric-character-reference";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-decode-numeric-character-reference/-/micromark-util-decode-numeric-character-reference-1.1.0.tgz";
        sha512 = "m9V0ExGv0jB1OT21mrWcuf4QhP46pH1KkfWy9ZEezqHKAxkj4mPCy3nIH1rkbdMlChLHX531eOrymlwyZIf2iw==";
      };
    };
    "micromark-util-decode-string-1.1.0" = {
      name = "micromark-util-decode-string";
      packageName = "micromark-util-decode-string";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-decode-string/-/micromark-util-decode-string-1.1.0.tgz";
        sha512 = "YphLGCK8gM1tG1bd54azwyrQRjCFcmgj2S2GoJDNnh4vYtnL38JS8M4gpxzOPNyHdNEpheyWXCTnnTDY3N+NVQ==";
      };
    };
    "micromark-util-encode-1.1.0" = {
      name = "micromark-util-encode";
      packageName = "micromark-util-encode";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-encode/-/micromark-util-encode-1.1.0.tgz";
        sha512 = "EuEzTWSTAj9PA5GOAs992GzNh2dGQO52UvAbtSOMvXTxv3Criqb6IOzJUBCmEqrrXSblJIJBbFFv6zPxpreiJw==";
      };
    };
    "micromark-util-html-tag-name-1.2.0" = {
      name = "micromark-util-html-tag-name";
      packageName = "micromark-util-html-tag-name";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-html-tag-name/-/micromark-util-html-tag-name-1.2.0.tgz";
        sha512 = "VTQzcuQgFUD7yYztuQFKXT49KghjtETQ+Wv/zUjGSGBioZnkA4P1XXZPT1FHeJA6RwRXSF47yvJ1tsJdoxwO+Q==";
      };
    };
    "micromark-util-normalize-identifier-1.1.0" = {
      name = "micromark-util-normalize-identifier";
      packageName = "micromark-util-normalize-identifier";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-normalize-identifier/-/micromark-util-normalize-identifier-1.1.0.tgz";
        sha512 = "N+w5vhqrBihhjdpM8+5Xsxy71QWqGn7HYNUvch71iV2PM7+E3uWGox1Qp90loa1ephtCxG2ftRV/Conitc6P2Q==";
      };
    };
    "micromark-util-resolve-all-1.1.0" = {
      name = "micromark-util-resolve-all";
      packageName = "micromark-util-resolve-all";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-resolve-all/-/micromark-util-resolve-all-1.1.0.tgz";
        sha512 = "b/G6BTMSg+bX+xVCshPTPyAu2tmA0E4X98NSR7eIbeC6ycCqCeE7wjfDIgzEbkzdEVJXRtOG4FbEm/uGbCRouA==";
      };
    };
    "micromark-util-sanitize-uri-1.2.0" = {
      name = "micromark-util-sanitize-uri";
      packageName = "micromark-util-sanitize-uri";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-sanitize-uri/-/micromark-util-sanitize-uri-1.2.0.tgz";
        sha512 = "QO4GXv0XZfWey4pYFndLUKEAktKkG5kZTdUNaTAkzbuJxn2tNBOr+QtxR2XpWaMhbImT2dPzyLrPXLlPhph34A==";
      };
    };
    "micromark-util-subtokenize-1.1.0" = {
      name = "micromark-util-subtokenize";
      packageName = "micromark-util-subtokenize";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-subtokenize/-/micromark-util-subtokenize-1.1.0.tgz";
        sha512 = "kUQHyzRoxvZO2PuLzMt2P/dwVsTiivCK8icYTeR+3WgbuPqfHgPPy7nFKbeqRivBvn/3N3GBiNC+JRTMSxEC7A==";
      };
    };
    "micromark-util-symbol-1.1.0" = {
      name = "micromark-util-symbol";
      packageName = "micromark-util-symbol";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-symbol/-/micromark-util-symbol-1.1.0.tgz";
        sha512 = "uEjpEYY6KMs1g7QfJ2eX1SQEV+ZT4rUD3UcF6l57acZvLNK7PBZL+ty82Z1qhK1/yXIY4bdx04FKMgR0g4IAag==";
      };
    };
    "micromark-util-types-1.1.0" = {
      name = "micromark-util-types";
      packageName = "micromark-util-types";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-types/-/micromark-util-types-1.1.0.tgz";
        sha512 = "ukRBgie8TIAcacscVHSiddHjO4k/q3pnedmzMQ4iwDcK0FtFCohKOlFbaOL/mPgfnPsL3C1ZyxJa4sbWrBl3jg==";
      };
    };
    "mime-2.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-2.6.0.tgz";
        sha512 = "USPkMeET31rOMiarsBNIHZKLGgvKc/LrjofAnBlOttf5ajRvqiRA8QsenbcooctK6d6Ts6aqZXBA+XbkKthiQg==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "mkdirp-0.5.6" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.6.tgz";
        sha512 = "FP+p8RB8OWpF3YZBCrP5gtADmtXApB5AMLn+vdyA+PyxCjrCs00mjyUozssO33cwDeT3wNGdLxJ5M//YqtHAJw==";
      };
    };
    "mri-1.2.0" = {
      name = "mri";
      packageName = "mri";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mri/-/mri-1.2.0.tgz";
        sha512 = "tzzskb3bG8LvYGFF/mDTpq3jpI6Q9wc3LEmBaghu+DdCssd1FakN7Bc0hVNmEyGq1bq3RgfkCb3cmQLpNPOroA==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha512 = "Tpp60P6IUJDTuOq/5Z8cdskzJujfwqfOTkrwIwj7IRISpnkJnT6SyJ4PCPnGMoFjC9ddhal5KVIYtAt97ix05A==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "nanolru-1.0.0" = {
      name = "nanolru";
      packageName = "nanolru";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanolru/-/nanolru-1.0.0.tgz";
        sha512 = "GyQkE8M32pULhQk7Sko5raoIbPalAk90ICG+An4fq6fCsFHsP6fB2K46WGXVdoJpy4SGMnZ/EKbo123fZJomWg==";
      };
    };
    "non-layered-tidy-tree-layout-2.0.2" = {
      name = "non-layered-tidy-tree-layout";
      packageName = "non-layered-tidy-tree-layout";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/non-layered-tidy-tree-layout/-/non-layered-tidy-tree-layout-2.0.2.tgz";
        sha512 = "gkXMxRzUH+PB0ax9dUN0yYF0S25BqeAYqhgMaLUFmpXLEk7Fcu8f4emJuOAY0V8kjDICxROIKsTAKsV/v355xw==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha512 = "AVbw3UJ2e9bq64vSaS9Am0fje1Pa8pbGqTTsmXfaIiMpnr5DlDhfJOuLj9Sf95ZPVDAUerDfEk88MPmPe7UCQg==";
      };
    };
    "pend-1.2.0" = {
      name = "pend";
      packageName = "pend";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pend/-/pend-1.2.0.tgz";
        sha512 = "F3asv42UuXchdzt+xXqfW1OGlVBe+mxa2mqI0pg5yAHZPvFmY3Y6drSf/GQ1A86WgWEN9Kzh/WrgKa6iGcHXLg==";
      };
    };
    "prettier-2.8.8" = {
      name = "prettier";
      packageName = "prettier";
      version = "2.8.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-2.8.8.tgz";
        sha512 = "tdN8qQGvNjw4CHbY+XXk0JgCXn9QiF21a55rBe5LJAU+kDyC4WQn4+awm2Xfk2lQMk5fKup9XgzTZtGkjBdP9Q==";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "progress-2.0.3" = {
      name = "progress";
      packageName = "progress";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/progress/-/progress-2.0.3.tgz";
        sha512 = "7PiHtLll5LdnKIMw100I+8xJXR5gW2QwWYkT6iJva0bXitZKa/XMrSbdmg3r2Xnaidz9Qumd0VPaMrZlF9V9sA==";
      };
    };
    "proxy-from-env-1.1.0" = {
      name = "proxy-from-env";
      packageName = "proxy-from-env";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-from-env/-/proxy-from-env-1.1.0.tgz";
        sha512 = "D+zkORCbA9f1tdWRK0RaCR3GPv50cMxcrz4X8k5LTSUD1Dkw47mKJEZQNunItRTkWwgtaUSo1RVFRIG9ZXiFYg==";
      };
    };
    "puppeteer-1.20.0" = {
      name = "puppeteer";
      packageName = "puppeteer";
      version = "1.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/puppeteer/-/puppeteer-1.20.0.tgz";
        sha512 = "bt48RDBy2eIwZPrkgbcwHtb51mj2nKvHOPMaSH2IsWiv7lOG9k9zhaRzpDZafrk05ajMc3cu+lSQYYOfH2DkVQ==";
      };
    };
    "readable-stream-2.3.8" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.8.tgz";
        sha512 = "8p0AUk4XODgIewSi0l8Epjs+EVnWiK7NoDIEGU0HhE7+ZyY8D1IMY7odu5lRrFXGg71L15KG8QrPmum45RTtdA==";
      };
    };
    "rimraf-2.7.1" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.7.1.tgz";
        sha512 = "uWjbaKIK3T1OSVptzX7Nl6PvQ3qAGtKEtVRjRuazjfL3Bx5eI409VZSqgND+4UNnmzLVdPj9FqFJNPqBZFve4w==";
      };
    };
    "robust-predicates-3.0.2" = {
      name = "robust-predicates";
      packageName = "robust-predicates";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/robust-predicates/-/robust-predicates-3.0.2.tgz";
        sha512 = "IXgzBWvWQwE6PrDI05OvmXUIruQTcoMDzRsOd5CDvHCVLcLHMTSYvOK5Cm46kWqlV3yAbuSpBZdJ5oP5OUoStg==";
      };
    };
    "rw-1.3.3" = {
      name = "rw";
      packageName = "rw";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/rw/-/rw-1.3.3.tgz";
        sha512 = "PdhdWy89SiZogBLaw42zdeqtRJ//zFd2PgQavcICDUgJT5oW10QCRKbJ6bg4r0/UY2M6BWd5tkxuGFRvCkgfHQ==";
      };
    };
    "sade-1.8.1" = {
      name = "sade";
      packageName = "sade";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sade/-/sade-1.8.1.tgz";
        sha512 = "xal3CZX1Xlo/k4ApwCFrHVACi9fBqJ7V+mwhBsuf/1IOKbBy098Fex+Wa/5QMubw09pSZ/u8EY8PWgevJsXp1A==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "stylis-4.2.0" = {
      name = "stylis";
      packageName = "stylis";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylis/-/stylis-4.2.0.tgz";
        sha512 = "Orov6g6BB1sDfYgzWfTHDOxamtX1bE/zo104Dh9e6fqJ3PooipYyfJ0pUmrZO2wAvO8YbEyeFrkV91XTsGMSrw==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-color-8.1.1" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "8.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-8.1.1.tgz";
        sha512 = "MpUEN2OodtUzxvKQl72cUF7RQ5EiHsGvSsVG0ia9c5RbWGL2CI4C7EpPS8UTBIplnlzZiNuV56w+FuNxy3ty2Q==";
      };
    };
    "ts-dedent-2.2.0" = {
      name = "ts-dedent";
      packageName = "ts-dedent";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ts-dedent/-/ts-dedent-2.2.0.tgz";
        sha512 = "q5W7tVM71e2xjHZTlgfTDoPF/SmqKG5hddq9SzR49CH2hayqRKJtQ4mtRlSxKaJlR/+9rEM+mnBHf7I2/BQcpQ==";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha512 = "/aCDEGatGvZ2BIk+HmLf4ifCJFwvKFNb9/JeZPMulfgFracn9QFcAf5GO8B/mweUjSoblS5In0cWhqpfs/5PQA==";
      };
    };
    "unist-util-stringify-position-3.0.3" = {
      name = "unist-util-stringify-position";
      packageName = "unist-util-stringify-position";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-stringify-position/-/unist-util-stringify-position-3.0.3.tgz";
        sha512 = "k5GzIBZ/QatR8N5X2y+drfpWG8IDBzdnVj6OInRNWm1oXrzydiaAT2OQiA8DPRRZyAKb9b6I2a6PxYklZD0gKg==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "uuid-9.0.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "9.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-9.0.0.tgz";
        sha512 = "MXcSTerfPa4uqyzStbRoTgt5XIe3x5+42+q1sDuy3R5MDk66URdLMOZe5aPX/SQd+kuYAh0FdP/pO28IkQyTeg==";
      };
    };
    "uvu-0.5.6" = {
      name = "uvu";
      packageName = "uvu";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/uvu/-/uvu-0.5.6.tgz";
        sha512 = "+g8ENReyr8YsOc6fv/NVJs2vFdHBnBNdfE49rshrTzDWOlUx4Gq7KOS2GD8eqhy2j+Ejq29+SbKH8yjkAqXqoA==";
      };
    };
    "web-worker-1.2.0" = {
      name = "web-worker";
      packageName = "web-worker";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/web-worker/-/web-worker-1.2.0.tgz";
        sha512 = "PgF341avzqyx60neE9DD+XS26MMNMoUQRz9NOZwW32nPQrF6p77f1htcnjBSEV8BGMKZ16choqUG4hyI0Hx7mA==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "ws-6.2.2" = {
      name = "ws";
      packageName = "ws";
      version = "6.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-6.2.2.tgz";
        sha512 = "zmhltoSR8u1cnDsD43TX59mzoMZsLKqUweyYBAIvTngR3shc0W6aOZylZmq/7hqyVxPdi+5Ud2QInblgyE72fw==";
      };
    };
    "yauzl-2.10.0" = {
      name = "yauzl";
      packageName = "yauzl";
      version = "2.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yauzl/-/yauzl-2.10.0.tgz";
        sha512 = "p4a9I6X6nu6IhoGmBqAcbJy1mlC4j27vEPZX9F4L4/vZT3Lyq1VkFHw/V/PUcB9Buo+DG3iHkT0x3Qya58zc3g==";
      };
    };
  };
in {
  "@fsouza/prettierd" = nodeEnv.buildNodePackage {
    name = "_at_fsouza_slash_prettierd";
    packageName = "@fsouza/prettierd";
    version = "0.23.4";
    src = fetchurl {
      url = "https://registry.npmjs.org/@fsouza/prettierd/-/prettierd-0.23.4.tgz";
      sha512 = "Kl1udnEO6Pz2teme/bhmW8PuaQrJI4q+b3YckYNL8EShGSo/cK3KpIIkx0OMS+vv/M5G2J/vNK6GD92cITp9fw==";
    };
    dependencies = [
      sources."core_d-5.0.1"
      sources."has-flag-4.0.0"
      sources."nanolru-1.0.0"
      sources."prettier-2.8.8"
      sources."supports-color-8.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "prettier, as a daemon";
      homepage = "https://github.com/fsouza/prettierd";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  mermaid = nodeEnv.buildNodePackage {
    name = "mermaid";
    packageName = "mermaid";
    version = "10.2.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/mermaid/-/mermaid-10.2.3.tgz";
      sha512 = "cMVE5s9PlQvOwfORkyVpr5beMsLdInrycAosdr+tpZ0WFjG4RJ/bUHST7aTgHNJbujHkdBRAm+N50P3puQOfPw==";
    };
    dependencies = [
      sources."@braintree/sanitize-url-6.0.2"
      sources."@types/debug-4.1.8"
      sources."@types/mdast-3.0.11"
      sources."@types/ms-0.7.31"
      sources."@types/unist-2.0.6"
      sources."character-entities-2.0.2"
      sources."commander-7.2.0"
      sources."cose-base-1.0.3"
      sources."cytoscape-3.25.0"
      sources."cytoscape-cose-bilkent-4.1.0"
      (sources."cytoscape-fcose-2.2.0"
        // {
          dependencies = [
            sources."cose-base-2.2.0"
            sources."layout-base-2.0.1"
          ];
        })
      sources."d3-7.8.5"
      sources."d3-array-3.2.4"
      sources."d3-axis-3.0.0"
      sources."d3-brush-3.0.0"
      sources."d3-chord-3.0.1"
      sources."d3-color-3.1.0"
      sources."d3-contour-4.0.2"
      sources."d3-delaunay-6.0.4"
      sources."d3-dispatch-3.0.1"
      sources."d3-drag-3.0.0"
      sources."d3-dsv-3.0.1"
      sources."d3-ease-3.0.1"
      sources."d3-fetch-3.0.1"
      sources."d3-force-3.0.0"
      sources."d3-format-3.1.0"
      sources."d3-geo-3.1.0"
      sources."d3-hierarchy-3.1.2"
      sources."d3-interpolate-3.0.1"
      sources."d3-path-3.1.0"
      sources."d3-polygon-3.0.1"
      sources."d3-quadtree-3.0.1"
      sources."d3-random-3.0.1"
      sources."d3-scale-4.0.2"
      sources."d3-scale-chromatic-3.0.0"
      sources."d3-selection-3.0.0"
      sources."d3-shape-3.2.0"
      sources."d3-time-3.1.0"
      sources."d3-time-format-4.1.0"
      sources."d3-timer-3.0.1"
      sources."d3-transition-3.0.1"
      sources."d3-zoom-3.0.0"
      sources."dagre-d3-es-7.0.10"
      sources."dayjs-1.11.8"
      sources."debug-4.3.4"
      sources."decode-named-character-reference-1.0.2"
      sources."delaunator-5.0.0"
      sources."dequal-2.0.3"
      sources."diff-5.1.0"
      sources."dompurify-3.0.3"
      sources."elkjs-0.8.2"
      sources."heap-0.2.7"
      sources."iconv-lite-0.6.3"
      sources."internmap-2.0.3"
      sources."khroma-2.0.0"
      sources."kleur-4.1.5"
      sources."layout-base-1.0.2"
      sources."lodash-4.17.21"
      sources."lodash-es-4.17.21"
      sources."mdast-util-from-markdown-1.3.1"
      sources."mdast-util-to-string-3.2.0"
      sources."micromark-3.2.0"
      sources."micromark-core-commonmark-1.1.0"
      sources."micromark-factory-destination-1.1.0"
      sources."micromark-factory-label-1.1.0"
      sources."micromark-factory-space-1.1.0"
      sources."micromark-factory-title-1.1.0"
      sources."micromark-factory-whitespace-1.1.0"
      sources."micromark-util-character-1.2.0"
      sources."micromark-util-chunked-1.1.0"
      sources."micromark-util-classify-character-1.1.0"
      sources."micromark-util-combine-extensions-1.1.0"
      sources."micromark-util-decode-numeric-character-reference-1.1.0"
      sources."micromark-util-decode-string-1.1.0"
      sources."micromark-util-encode-1.1.0"
      sources."micromark-util-html-tag-name-1.2.0"
      sources."micromark-util-normalize-identifier-1.1.0"
      sources."micromark-util-resolve-all-1.1.0"
      sources."micromark-util-sanitize-uri-1.2.0"
      sources."micromark-util-subtokenize-1.1.0"
      sources."micromark-util-symbol-1.1.0"
      sources."micromark-util-types-1.1.0"
      sources."mri-1.2.0"
      sources."ms-2.1.2"
      sources."non-layered-tidy-tree-layout-2.0.2"
      sources."robust-predicates-3.0.2"
      sources."rw-1.3.3"
      sources."sade-1.8.1"
      sources."safer-buffer-2.1.2"
      sources."stylis-4.2.0"
      sources."ts-dedent-2.2.0"
      sources."unist-util-stringify-position-3.0.3"
      sources."uuid-9.0.0"
      sources."uvu-0.5.6"
      sources."web-worker-1.2.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Markdown-ish syntax for generating flowcharts, sequence diagrams, class diagrams, gantt charts and git graphs.";
      homepage = "https://github.com/mermaid-js/mermaid#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "mermaid.cli" = nodeEnv.buildNodePackage {
    name = "mermaid.cli";
    packageName = "mermaid.cli";
    version = "0.5.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/mermaid.cli/-/mermaid.cli-0.5.1.tgz";
      sha512 = "03aKyM1nH86Hk16xiP7Hiswg2CuJ4iFkwDdWln00Irx4E81fy1FPUzXon3JVckp1MkxKtDHJlg3SudlLwKsndQ==";
    };
    dependencies = [
      sources."agent-base-4.3.0"
      sources."ansi-styles-3.2.1"
      sources."async-limiter-1.0.1"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.11"
      sources."buffer-crc32-0.2.13"
      sources."buffer-from-1.1.2"
      sources."chalk-2.4.2"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."commander-2.20.3"
      sources."concat-map-0.0.1"
      sources."concat-stream-1.6.2"
      sources."core-util-is-1.0.3"
      sources."debug-4.3.4"
      sources."es6-promise-4.2.8"
      sources."es6-promisify-5.0.0"
      sources."escape-string-regexp-1.0.5"
      (sources."extract-zip-1.7.0"
        // {
          dependencies = [
            sources."debug-2.6.9"
            sources."ms-2.0.0"
          ];
        })
      sources."fd-slicer-1.1.0"
      sources."fs.realpath-1.0.0"
      sources."glob-7.2.3"
      sources."has-flag-3.0.0"
      (sources."https-proxy-agent-2.2.4"
        // {
          dependencies = [
            sources."debug-3.2.7"
          ];
        })
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."isarray-1.0.0"
      sources."mime-2.6.0"
      sources."minimatch-3.1.2"
      sources."minimist-1.2.8"
      sources."mkdirp-0.5.6"
      sources."ms-2.1.2"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."pend-1.2.0"
      sources."process-nextick-args-2.0.1"
      sources."progress-2.0.3"
      sources."proxy-from-env-1.1.0"
      sources."puppeteer-1.20.0"
      sources."readable-stream-2.3.8"
      sources."rimraf-2.7.1"
      sources."safe-buffer-5.1.2"
      sources."string_decoder-1.1.1"
      sources."supports-color-5.5.0"
      sources."typedarray-0.0.6"
      sources."util-deprecate-1.0.2"
      sources."wrappy-1.0.2"
      sources."ws-6.2.2"
      sources."yauzl-2.10.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Command-line interface for mermaid";
      homepage = "https://github.com/mermaidjs/mermaid.cli#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
