name: "Test Marsh-Framework"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # v8 only works? https://github.com/DeterminateSystems/nix-installer-action/issues/60
      - uses: DeterminateSystems/nix-installer-action@v8
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix build .#nixosConfigurations.marsh-framework.config.system.build.toplevel
